version: '3'
services:
  # app:
  #   build: .
  #   working_dir: /usr/src/app/src
  #   volumes:
  #     - .:/usr/src/app
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - mysql
  #   env_file:
  #     - .env
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
